// 2469-Gautam-Feb22/Angular/Day3/Practice/Calc/Source/calc/src/app/calc/calc.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-calc',
  templateUrl: './calc.component.html',
  styleUrls: ['./calc.component.css']
})
export class CalcComponent implements OnInit {

  num1:number=0;
  num2:number=0;
  add="";
  sub="";
  mul="";

  result(){
    this.add="Addition is : " + (this.num1+this.num2);
    this.sub="Subtraction is : " + (this.num1-this.num2);
    this.mul="Multlipication is : " + this.num1*this.num2;
  }

  constructor() {

  
   }

  ngOnInit(): void {
  
  }

}


<label for="fno">Enter First No.</label>
<input type="number" [(ngModel)]="num1"><br/><br/>
<label for="sno">Enter Second No.</label>
<input type="number" [(ngModel)]="num2"><br/><br/>
<button (click)="result()">Calculate</button>

<p>Number 1 : {{num1}}</p>
<p>Number 2 : {{num2}}</p>

<div id="ans">
<p>{{add}} </p>
<p>{{sub}} </p>
<p>{{mul}} </p>
</div>

// 2469-Gautam-Feb22/Vue/Day3/Practice/calc/Source/calc/src/components/calc.vue
<template>
  <div>
    <label for="fno">Enter First No.</label>
    <input type="number" v-model="num1" /><br /><br />
    <label for="sno">Enter Second No.</label>
    <input type="number" v-model="num2" /><br /><br />
    <button v-on:click="result()">Calculate</button>

    <p>Number 1 : {{ num1 }}</p>
    <p>Number 2 : {{ num2 }}</p>

    <div id="ans">
      <p>{{ add }}</p>
      <p>{{ sub }}</p>
      <p>{{ mul }}</p>
    </div>
  </div>
</template>

<script>
export default {
    name: 'CalcComponent',
    data() {
    return {
             num1: 0,
            num2:0,
            add :'',
            sub :'',
            mul:'',

  result() {
    this.add = 'Addition is : ' + (this.num1 + this.num2);
    this.sub = 'Subtraction is : ' + (this.num1 - this.num2);
    this.mul = 'Multlipication is : ' + this.num1 * this.num2;
  }

    }

}
}
</script>

<style>
#ans {
  color: blue;
}
</style>
