// 2469-Gautam-Feb22/Angular/Day3/Assignment/day3assi/Source/day3assi/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  uname = "";
  pass = "";
  check() {
    if (this.uname == "" || this.pass == ""){
      alert("Username and Password Should not be Blank");
    }
    else if (this.uname == "admin" && this.pass == "admin") {
      alert("Valid User");
      this.uname = "";
      this.pass = "";
    }
    else {
      alert("Invalid User");
      this.uname = "";
      this.pass = "";
    }
  }
  constructor() { }

  ngOnInit(): void {
  }

}

// 2469-Gautam-Feb22/Vue/Day3/Assignment/day3Assi/Source/day3assi/src/components/login.vue
<template>
  <div id="login" class="col-4 d-inline-block vh-100">
    <h6 class="pb-3">
      Create Login Component which validate a user with below credential
      username=admin, password=admin
    </h6>
    <p>
      Enter Username :
      <input type="text" placeholder="UserName" v-model="uname" required />
    </p>
    <p>
      Enter Password :
      <input type="text" placeholder="Password" v-model="pass" required />
    </p>
    <button v-on:click="check()" class="btn btn-primary">Submit</button>
  </div>
</template>

<script>
export default {
      name: 'loginComponent',
      data(){
          return{
              uname:"",
              pass:"",
              check(){
                  if (this.uname == "" || this.pass == ""){
                        alert("Username and Password Should not be Blank");
                    }
                else if (this.uname == "admin" && this.pass == "admin") {
                         alert("Valid User");
                            this.uname = "";
                         this.pass = "";
                    }
                else {
                        alert("Invalid User");
                        this.uname = "";
                        this.pass = "";
                    }
                }

              }
          }
}
</script>

<style>
</style>
