// 2469-Gautam-Feb22/Angular_React_Vue/Day16/Practice/React/Source/authgaurdpractice/src/App.js
import { Link, Outlet } from "react-router-dom";
import React, { useState } from "react";
import "./App.css";

function App() {
  const [user, setUser] = useState("");
  const [password, setPassword] = useState("");
  function logIn(user,password){
    console.log(user,password)
    if(user=="admin" && password=="password")
    localStorage.setItem('username', user);
    else
    alert("Incorrect details")
  }
  function logout() {
    localStorage.removeItem('username');
  }
  return (
    <div>
      <div>
        <p>username : admin, Password : password</p>
        username :
        <input
          type="text"
          value={user}
          onChange={(e) => setUser(e.target.value)}
        />
        <br/>
        Password :
        <input
          type="text"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <button  onClick={()=>logIn(user,password)}>Login</button>
        <button  onClick={()=>logout()}>logout</button>
        
      </div>

      <nav>
        <Link to="/home">HOME</Link> <br />
        <Link to="/about">ABOUT</Link> <br />
        <Link to="/protected">PROTECTED</Link>
      </nav>

      <Outlet></Outlet>
    </div>
  );
}

export default App;

// 2469-Gautam-Feb22/Angular_React_Vue/Day16/Assignments/Vue/Source/rolebasedlogin/src/App.vue
<script>

export default{
   data(){
    return{
      username:"",
      password:""
    }
  },
  methods:{
    login(){
      if((this.username == "admin" || this.username == 'user') && this.password == "password"){
      localStorage.setItem("username",this.username);
      alert("Login Succesfully");
      }
      else{
        alert('Incorrect Details')
      }
    },
  
    getUser() {
    return localStorage.getItem('username');
  }
  }
  }
</script>

<template>
  <header>  
      <p>UserName : user / admin , Password = password</p>
       <div>
      UserName : <input type="text" v-model="username" />
      Password : <input type="text" v-model="password" />
      <button type="submit" @click="login()">Login</button>
      
      </div>
      <nav>
        <RouterLink to="/">Home</RouterLink> <br>
        <RouterLink to="/user">User</RouterLink> <br>
         <RouterLink to="/admin">Admin</RouterLink>
      </nav>
        <RouterView />
  </header>

</template>

<style>

</style>
