// 2469-Gautam-Feb22/Vue/Day4/Practice/GreaterofTwo/Source/greateroftwo/src/components/GreaterofTwo.vue
<template>
  <div>
    <h2>Find out greater of two number</h2>
    <button v-on:click="show = !show">{{ show ? "hide" : "show" }}</button>

    <div v-if="show">
      <p>Number 1 : <input type="number" v-model="num1" /></p>
      <p>Number 2 : <input type="number" v-model="num2" /></p>
      <p>Number 1 : {{ num1 }}, Number 2 : {{ num2 }}</p>

      <div v-if="compare()">
        <p>Number1 {{ num1 }} is Large</p>
      </div>
      <div v-else>Number2 {{ num2 }} is Large</div>
    </div>
  </div>
</template>

<script>
export default {
    name:"GreaterofTwo",
    data(){
       return{
            num1:20,
            num2:30,
            show:true,

            compare() {
            return this.num1 > this.num2;
            },
       };
       },
};
</script>

<style>
</style>

// 2469-Gautam-Feb22/React/Day5/Practice/greateroftwo/Source/greateroftwo/src/components/GreaterofTwo.js
import React, { useState } from 'react';
export default function () {
  const [num1, setNum1] = useState(0);
  const [num2, setNum2] = useState(1);
  return (
    <div>
      <h2>Find out greater of two number</h2>
      <p>
        Number 1 :
        <input
          type="text"
          value={num1}
          onChange={(e) => setNum1(parseInt(e.target.value))}
        />
      </p>
      <p>
        Number 2 :
        <input
          type="text"
          value={num2}
          onChange={(e) => setNum2(parseInt(e.target.value))}
        />
      </p>

      {num1 > num2 ? (
        <h3>
          {num1} is Greater than {num2}
        </h3>
      ) : (
        <h3>
          {num2} is Greater than {num1}
        </h3>
      )}
    </div>
  );
}
