// 2469-Gautam-Feb22/Angular_React_Vue/Day16/Practice/Vue/Source/authgaurdpractice/src/App.vue
<script>
import { RouterLink, RouterView } from 'vue-router'

export default{
  data(){
    return{
      username:"",
      password:""
    }
  },
  methods:{
    login(){
      if(this.username == "admin" && this.password == "password"){
      localStorage.setItem("user",this.username);
      alert("Login Succesfully");
      }
      else{
        alert('Incorrect Details')
      }
    },
    logout(){
      localStorage.removeItem('user');
    },
    getUser() {
    return localStorage.getItem('user');
  }
  }
}
</script>

<template>
  <header>  
    <p>UserName : admin , Password : password</p>
    <div>
      UserName : <input type="text" v-model="username" />
      Password : <input type="text" v-model="password" />
      <button type="submit" @click="login()">Login</button>
      <button type="button" @click="logout()">LogOut</button>
    </div>


      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
         <RouterLink to="/protected">Protected</RouterLink>
      </nav>
        <RouterView />
  </header>

</template>

<style>

</style>

// 2469-Gautam-Feb22/Angular_React_Vue/Day15/Practice/Angular/Source/greetingservice/src/app/app.component.ts
import { Component } from '@angular/core';
import { AuthServiceService } from './auth-service.service';
import { GreetingService } from './greeting.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'greetingservice';
  user='';
  greetings = '';
  uname='';
  password='';

  constructor(private gt:GreetingService,public authServive:AuthServiceService){ 
  }

  login(){
    this.authServive.login(this.uname,this.password)
  }
  logout(){
    this.authServive.logout();
  }
  
  sendName(){
    this.greetings=this.gt.greetings(this.user)
  }
}

Enter Name : <input type="text" [(ngModel)]="user"/>
<button (click)="sendName()">Submit</button>
<p>{{greetings}}</p>

<br>
<hr/>
<p>AuthGauards in Angular</p>
<div class="navbar-nav">
    <a [routerLink]="['/home']">Home</a> 
    <a [routerLink]="['/about-us']">About</a>
    <a [routerLink]="['/protected']">Protected</a>
  </div>

  <div *ngIf="authServive.getUser()"><button  (click)="logout()">LogOut</button></div>

  <div *ngIf="!authServive.getUser()">


  <form class="form-inline" >
    <div class="form-group">
      <label for="username">User:</label>
      <input class="form-control" name="username" [(ngModel)]="uname">
    </div>

    <div class="form-group">
      <label for="password">Password:</label>
      <input class="form-control" type="password" name="password" [(ngModel)]="password">
    </div>

    <a class="btn btn-default" (click)="login()">
      Submit
    </a>
  </form>
</div>
  <router-outlet></router-outlet>
