// 2469-Gautam-Feb22/Angular_React_Vue/Day16/Practice/Vue/Source/authgaurdpractice/src/App.vue
<script>
import { RouterLink, RouterView } from 'vue-router'

export default{
  data(){
    return{
      username:"",
      password:""
    }
  },
  methods:{
    login(){
      if(this.username == "admin" && this.password == "password"){
      localStorage.setItem("user",this.username);
      alert("Login Succesfully");
      }
      else{
        alert('Incorrect Details')
      }
    },
    logout(){
      localStorage.removeItem('user');
    },
    getUser() {
    return localStorage.getItem('user');
  }
  }
}
</script>

<template>
  <header>  
    <p>UserName : admin , Password : password</p>
    <div>
      UserName : <input type="text" v-model="username" />
      Password : <input type="text" v-model="password" />
      <button type="submit" @click="login()">Login</button>
      <button type="button" @click="logout()">LogOut</button>
    </div>


      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
         <RouterLink to="/protected">Protected</RouterLink>
      </nav>
        <RouterView />
  </header>

</template>

<style>

</style>

// 2469-Gautam-Feb22/Angular_React_Vue/Day16/Practice/React/Source/authgaurdpractice/src/App.js
import { Link, Outlet } from "react-router-dom";
import React, { useState } from "react";
import "./App.css";

function App() {
  const [user, setUser] = useState("");
  const [password, setPassword] = useState("");
  function logIn(user,password){
    console.log(user,password)
    if(user=="admin" && password=="password")
    localStorage.setItem('username', user);
    else
    alert("Incorrect details")
  }
  function logout() {
    localStorage.removeItem('username');
  }
  return (
    <div>
      <div>
        <p>username : admin, Password : password</p>
        username :
        <input
          type="text"
          value={user}
          onChange={(e) => setUser(e.target.value)}
        />
        <br/>
        Password :
        <input
          type="text"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <button  onClick={()=>logIn(user,password)}>Login</button>
        <button  onClick={()=>logout()}>logout</button>
        
      </div>

      <nav>
        <Link to="/home">HOME</Link> <br />
        <Link to="/about">ABOUT</Link> <br />
        <Link to="/protected">PROTECTED</Link>
      </nav>

      <Outlet></Outlet>
    </div>
  );
}

export default App;
