// 2469-Gautam-Feb22/Angular_React_Vue/Day7/Practice/Vue/Source/childtoparent/src/components/ProfileComp.vue
<template>
<div>
  <p>profile Component!</p>
    <p>Enter Value to pass Parent Component :
    <input type="text" v-model="name"> <br/>
    <button @click="submitInfo()">Submit</button>
    </p>
    <p>{{name}}</p> 
    </div>

</template>

<script>
export default {
name: "ProfileComp",
   data() {
    return {
    name:""
    }
   },
   methods:{
       submitInfo(){
           this.$emit('getinfo',this.name)
       }
   }
}
</script>

<style>

</style>

// 2469-Gautam-Feb22/React/Day7/Practice/childtoparent/Source/childtoparent/src/components/ProfileComp.js
import React, { useState } from 'react';
export default function (props) {
  const [name, setName] = useState();
  function demo() {
    props.getdata(name);
  }
  return (
    <div>
      <p>profile Component!</p>
      <p>
        Enter Value to pass Parent Component :
        <input type="text" onChange={(e) => setName(e.target.value)} />
      </p>
      <button onClick={demo}>SUBMIT</button>
      <p>{name}</p>
    </div>
  );
}
