// 2469-Gautam-Feb22/Angular_React_Vue/Day7/Practice/Vue/Source/childtoparent/src/App.vue
<template>
<div>
    <p>App Component ! </p>
    <h1>{{name}}</h1>
    <ProfileComp @getinfo="display($event)" ></ProfileComp>
</div>
</template>

<script>
import ProfileComp from './components/ProfileComp.vue'

export default {
  name: 'App',
  data(){
    return{
      name:""
    };
  },
  components: {
    ProfileComp
  },
  methods:{
    display(name)
    {
      this.name=name;
    }
  }
}
</script>

<style>

</style>

// 2469-Gautam-Feb22/React/Day7/Practice/childtoparent/Source/childtoparent/src/App.js
import React, { useState } from 'react';
import './App.css';
import ProfileComp from './components/ProfileComp';

function App() {
  const [name, setName] = useState();
  function display(data) {
    setName(data);
  }
  return (
    <div>
      <p>App Component !</p>
      <h1>{name}</h1>
      <ProfileComp getdata={display}></ProfileComp>
    </div>
  );
}

export default App;
