// 2469-Gautam-Feb22/Angular_React_Vue/Day2/Practice/React/Source/newcomponent/src/components/Alphabet.js
import React, { Component } from 'react';
var name = 'Print Alphabets from custom Component';
function printAlphabets(){
  var i = 65;
  var j = 91;
  var str;
  var res= '';
  for (var k = i; k < j; k++) {
    str = String.fromCharCode(k);
    res += str + ' ';
  }
  return res;
}
class Alphabet extends Component {
    state = {  } 
    render() { 
        return (
            <div>
            <p>Task : { name }</p>
            <p>{ printAlphabets() }</p>
            </div>
        );
    }
}
 
export default Alphabet;

// 2469-Gautam-Feb22/Angular/Day2/Practice/NewComponent/Source/newcomponent/src/app/alphabet/alphabet.component.ts
import { Component} from '@angular/core';

@Component({
  selector: 'app-alphabet',
  templateUrl: './alphabet.component.html',
  styleUrls: ['./alphabet.component.css']
})
export class AlphabetComponent{

  name="Print Alphabets from custom Component";
  printAlphabets() {
    var i=65;
    var j=91;
    var str;
    var res:string='';
    for(var k=i;k<j;k++){
      str=String.fromCharCode(k);
      res+=str+" ";
    }
    return res;
  }
  
}
