// 2469-Gautam-Feb22/Angular_React_Vue/AdditionalAssignment/Assignments/Angular/Source/studentevaluation/src/app/studentlist/studentlist.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-studentlist',
  templateUrl: './studentlist.component.html',
  styleUrls: ['./studentlist.component.css']
})
export class StudentlistComponent implements OnInit {
  id: number = 0;
  finallist: Array<any> = [];
  allentries: Array<any> = [];
  filterdlist: any[] = [];
  obtmark = '';
  currdate = '';

  selectedName = '';
  finalName: any;

  studentlist: any[] = [
    {
      id: '1',
      Name: 'ABC',
    },
    {
      id: '2',
      Name: 'XYZ',
    },
    {
      id: '3',
      Name: 'PQR',
    },
  ];

  standardlist: any[] = [
    {
      Standard: '1',
      Name: '',
      units: [
        {
          Unit: '',
        },
        { Unit: '' },
      ],
    },
    {
      Standard: '2',
      Name: '',
      units: [
        {
          Unit: '',
        },
        { Unit: '' },
        { Unit: '' },
        { Unit: '' },
      ],
    },
    {
      Standard: '3',
      Name: '',
      units: [
        {
          Unit: '',
        },
        { Unit: '' },
        { Unit: '' },
        { Unit: '' },
        { Unit: '' },
        { Unit: '' },
      ],
    },
  ];

  onSubmit() {
    console.warn(this.finallist);
    let temp = JSON.parse(JSON.stringify(this.finallist));
    this.allentries.push(temp);
    this.onClear();
  }

  onClear() {
    this.finallist.map((item) => (item.Name = ''));
    this.finallist.map((item) => item.units.map((i:any) => (i.Unit = '')));
  }

  printResult(entry: any) {
    this.filterdlist = [];
    this.filterdlist.push(entry);
    console.log(entry);
    this.currdate = new Date().toDateString();
  }

  calculateobtained(units: any) {
    console.log(units);
    return units
      .map((item:any) => item.Unit)
      .reduce((prev:any, curr:any) => parseInt(prev) + parseInt(curr));
  }

  constructor(private activeroute: ActivatedRoute) {}

  ngOnInit() {
    this.activeroute.params.subscribe((p) => {
      this.id = p['stdId'];
      this.finallist = this.standardlist.filter((p) => p.Standard == this.id);
    });
  }
}

<h3>Standard : {{ id }}</h3>
<div>
  <div *ngFor="let item of finallist" class="container">
    <label for="select">Select Student : </label>
    <select [(ngModel)]="item.Name" class="w-25">
      <option value="">select</option>
      <option *ngFor="let s of studentlist" value="{{ s.Name }}">
        {{ s.Name }}
      </option>
    </select>
    <br />
    <br />
    <ul *ngFor="let l of item.units; let i = index" class="list-unstyled">
      <li>
        <label for="item-{{ i }}"
          >Unit {{ i + 1 }} :<span class="required">*</span></label
        >
        <input
          id="item-{{ i }}"
          class="w-50"
          type="text"
          [(ngModel)]="l.Unit"
        />
      </li>
    </ul>
  </div>

  <button type="submit" class="rounded btn-primary" (click)="onSubmit()">
    Submit
  </button>
  <button type="button" class="rounded btn-danger" (click)="onClear()">
    Reset
  </button>
</div>
<hr />

<table class="w-50 table-bordered" *ngIf="allentries.length">
  <caption>
    ALL ENTRIES
  </caption>
  <tr>
    <th>Name</th>
    <th>Standard</th>
    <th>Result</th>
  </tr>
  <tbody *ngFor="let item of allentries">
    <tr *ngFor="let entry of item">
      <td>{{ entry.Name }}</td>
      <td>{{ entry.Standard }}</td>
      <td>
        <button class="btn-primary" (click)="printResult(entry)">Print</button>
      </td>
    </tr>
  </tbody>
</table>

<div class="text-center">
  <table class="w-50 table table-bordered text-center">
    <caption>
      RESULT
    </caption>
    <tbody *ngFor="let entry of filterdlist">
      <tr>
        <th colspan="2">ABC SCHOOL</th>
      </tr>
      <tr>
        <td>Name : {{ entry.Name }}</td>
        <td>Standard : {{ entry.Standard }}</td>
      </tr>
      <tr>
        <td colspan="2">{{ currdate }}</td>
      </tr>
      <tr *ngFor="let m of entry.units; let i = index">
        <td>Unit {{ i + 1 }}</td>
        <td>{{ m.Unit }}</td>
      </tr>
      <tr>
        <td colspan="2">Total Mark : {{ entry.units.length * 100 }}</td>
      </tr>
      <tr>
        <td colspan="2">
          Obtained Mark : {{ calculateobtained(entry.units) }}
        </td>
      </tr>
    </tbody>
  </table>
</div>

// 2469-Gautam-Feb22/Angular_React_Vue/AdditionalAssignment/Assignments/Vue/Source/studentevaluation/src/components/StudentList.vue
<template>
  <div>
    <hr />
    <p>Standard : {{ this.$route.params.std }}</p>

    <div v-for="item in finallist" :key="item" class="container">
      <label for="select">Select Student : </label>
      <select v-model="item.Name" class="w-25">
        <option value="">select</option>
        <option v-for="s in studentlist" :key="s" :value="s.Name">
          {{ s.Name }}
        </option>
      </select>
      <br />
      <br />
      <ul v-for="(l,index) in item.units" :key="l" class="list-unstyled">
        <li>
          <label for="item-{{index+1}}"
            >Unit {{index+1}}  :<span class="required">*</span></label
          >
          <input id="item" class="w-50" type="text" v-model="l.Unit" />
        </li>
      </ul>
    </div>
    <div class="container">
     <button type="submit" class="rounded btn-primary" @click="onSubmit()">
    Submit
  </button>
  <button type="button" class="rounded btn-danger" @click="onClear()">
    Reset
  </button>
  </div>
  <hr>
  {{finallist}}
  <hr>
  <table class="w-50 table-bordered" v-if="allentries.length">
  <caption>
    ALL ENTRIES
  </caption>
  <tr>
    <th>Name</th>
    <th>Standard</th>
    <th>Result</th>
  </tr>
  <tbody v-for="item in allentries" :key="item.Name">
    <tr v-for="entry in item" :key="entry">
      <td>{{ entry.Name }}</td>
      <td>{{ entry.Standard }}</td>
      <td>
        <button class="btn-primary" @click="printResult(entry)">Print</button>
      </td>
    </tr>
  </tbody>
</table>

  <div class="text-center">
  <table class="w-50 table table-bordered text-center">
    <caption>
      RESULT
    </caption>
    <tbody v-for="entry in filterdlist" :key="entry">
      <tr>
        <th colspan="2">ABC SCHOOL</th>
      </tr>
      <tr>
        <td>Name : {{ entry.Name }}</td>
        <td>Standard : {{ entry.Standard }}</td>
      </tr>
      <tr>
        <td colspan="2">{{ currdate }}</td>
      </tr>
      <tr v-for="(m,index) in entry.units" :key="m">
        <td>Unit {{ index + 1 }}</td>
        <td>{{ m.Unit }}</td>
      </tr>
      <tr>
        <td colspan="2">Total Mark : {{ entry.units.length * 100 }}</td>
      </tr>
      <tr>
        <td colspan="2">
          Obtained Mark : {{ calculateobtained(entry.units) }}
        </td>
      </tr>
    </tbody>
  </table>
</div>
  </div>
</template>

<script>
export default {
  name: "StudentList",
  props: {
    std: Number,
  },
  data() {
    return {
      selectedName: "",
      allentries:[],
        filterdlist:[],
  obtmark:'',
  currdate:'',
      studentlist: [
        {
          id: "1",
          Name: "ABC",
        },
        {
          id: "2",
          Name: "XYZ",
        },
        {
          id: "3",
          Name: "PQR",
        },
      ],
      standardlist: [
        {
          Standard: "1",
          Name: "",
          units: [
            {
              Unit: "",
            },
            { Unit: "" },
          ],
        },
        {
          Standard: "2",
          Name: "",
          units: [
            {
              Unit: "",
            },
            { Unit: "" },
            { Unit: "" },
            { Unit: "" },
          ],
        },
        {
          Standard: "3",
          Name: "",
          units: [
            {
              Unit: "",
            },
            { Unit: "" },
            { Unit: "" },
            { Unit: "" },
            { Unit: "" },
            { Unit: "" },
          ],
        },
      ],
    };
  },
  methods:{
      onSubmit() {
      console.warn(this.finallist);
      let temp = JSON.parse(JSON.stringify(this.finallist));
        this.allentries.push(temp);
       this.onClear();
  },

  onClear() {
    this.finallist.map((item) => (item.Name = ''));
    this.finallist.map((item) => item.units.map((i) => (i.Unit = '')));
  },
    printResult(entry) {
    this.filterdlist = [];
    this.filterdlist.push(entry);
    console.log(entry);
    this.currdate = new Date().toDateString();
  },
    calculateobtained(units) {
    return units
      .map((item) => item.Unit)
      .reduce((prev, curr) => parseInt(prev) + parseInt(curr));
  }
  },
  computed:{
    finallist(){
      return this.standardlist.filter((p)=>p.Standard==this.$route.params.std)
    }
  }
};
</script>

<style>
</style>
